CREATE DATABASE VEHICULOS
GO
USE VEHICULOS
GO
CREATE TABLE MATRICULAS
(
	ID INT IDENTITY(1,1),
	NUMERO VARCHAR(20)PRIMARY KEY NOT NULL,
	FECHA_EXPEDICION DATE NOT NULL,
	VALIDA_HASTA DATE NOT NULL,
	ESTADO BIT
)
GO
CREATE TABLE CONDUCTORES
(
	ID INT IDENTITY(1,1),
	IDENTIFICACION VARCHAR(15) PRIMARY KEY NOT NULL,
	NOMBRE VARCHAR(20) NOT NULL, 
	APELLIDO VARCHAR(20) NOT NULL,
	DIRECCION VARCHAR(30),
	TELEFONO VARCHAR(15),
	EMAIL VARCHAR(30),
	FECHA_NACIMIENTO DATE,
	ESTADO BIT, 
	NUMERO_MATRICULA VARCHAR(20) FOREIGN KEY 
	REFERENCES MATRICULAS(NUMERO)
	ON UPDATE CASCADE
)
GO
CREATE TABLE SANCIONES
(
	ID INT IDENTITY(1,1)PRIMARY KEY,
	FECHA_ACTUAL DATE DEFAULT GETDATE(),
	SANCION VARCHAR(100),
	OBSERVACION VARCHAR(MAX) NOT NULL,
	VALOR DECIMAL(10,2),
	CONDUCTOR_ID VARCHAR(15) FOREIGN KEY
	REFERENCES CONDUCTORES(IDENTIFICACION)
	ON UPDATE CASCADE
)
